export default {
  cooperationWorks: (state) => state.cooperationWorks,
  cooperationRequests: (state) => state.cooperationRequests,
  cooperationDocuments: (state) => state.cooperationDocuments,
  cooperationSpecifications: (state) => state.cooperationSpecifications,
  cooperationProgress: (state) => state.cooperationProgress,
  cooperationDocumentsFoundation: (state) => state.cooperationDocumentsFoundation,
  govCustomers: (state) => state.govCustomers,
  subcontractor: (state) => state.subcontractor,
  recipient: (state) => state.recipient,
  helicopter: (state) => state.helicopter,
  statusContract: (state) => state.statusContract,
  statusSupply: (state) => state.statusSupply,
  statusStage: (state) => state.statusStage,
  statusSpecification: (state) => state.statusSpecification,
  cooperationAgrees: (state) => state.cooperationAgrees,
  workType: (state) => state.workType,
  workName: (state) => state.workName,
};
