export default {
  cooperationWorks: null,
  cooperationRequests: null,
  cooperationDocuments: null,
  cooperationSpecifications: null,
  cooperationProgress: null,
  cooperationDocumentsFoundation: null,
  cooperationAgrees: null,
  workType: null,
  workName: null,
  govCustomers: null,
  subcontractor: null,
  recipient: null,
  helicopter: null,
  statusContract: null,
  statusSupply: null,
  statusStage: null,
  statusSpecification: null,
};
