export default {
  catalog: (state) => state.catalog,
  workType: (state) => state.workType,
  workName: (state) => state.workName,
  govCustomers: (state) => state.govCustomers,
  subcontractor: (state) => state.subcontractor,
  recipient: (state) => state.recipient,
  helicopter: (state) => state.helicopter,
  catalogComponents: (state) => state.catalogComponents,
  catalogUnits: (state) => state.catalogUnits,
  catalogContract: (state) => state.catalogContract,
  statusContract: (state) => state.statusContract,
  statusSupply: (state) => state.statusSupply,
  statusStage: (state) => state.statusStage,
  statusSpecification: (state) => state.statusSpecification,
  catalogStandarts: (state) => state.catalogStandarts,
  statusAdjustment: (state) => state.statusAdjustment,
  agency: (state) => state.agency,
  controlPoints: (state) => state.controlPoints,
  currentRevision:(state) => state.currentRevision,
};
