export default {
  catalog: null,
  workType: null,
  workName: null,
  govCustomers: null,
  subcontractor: null,
  recipient: null,
  helicopter: null,
  helicopterTypes: null,
  catalogComponents: null,
  catalogUnits: null,
  catalogContract: null,
  statusContract: null,
  statusSupply: null,
  statusStage: null,
  statusSpecification: null,
  catalogStandarts: null,
  statusAdjustment: null,
  agency: null,
  controlPoints: null,
  currentRevision: null,
};
